### ISSUE TITLE
Users vs People

### ISSUE THREAD

**Issue by sjmcculloch** [NSWSESMembers/availability-poc#120]
In the [current data model](https://github.com/NSWSESMembers/availability-poc/wiki/Release-1.0-Data-Model), all users must have a login/password but in reality _some_ people responding may not be users of the app (they will respond in other ways, e.g. phone, SMS, etc).

In other systems, they separate Users & People (1 to 1 relationship) for this reason. Should this app adopt the same approach and more importantly, do we need people who are not users of the app in the data model? (this applies to an instance of an app integrated to an existing operational system)

**Comment by sdunster** [comment]
This is a great question. I'm trying to keep it simple for now but you're right that it might be easier to do the separation now rather than later.
I thought for a while about making users exist outside of organisations too so that you could have one account that can be used for multiple organisations but I'm not sure the complexity is worth it. If we were to build on both ideas we could have "user" accounts that exist separate to organisations and a "person" that is created for each organisation that a user is a member of.

I don't intend to build support for any of these other systems (manual entry of responding users by SHQ, response via SMS etc) for launch so I tend to think we should leave that complexity out for now. The way I saw a solution like this used at KMA was that it was used to coordinate operational response using the information that it had but the team leader always supplemented it with information gathered from other systems as well (people would often manually SMS the team leader or call the duty officer). I see the app being adopted organically anyway whereby only part of each unit use it to begin with. If (after launch) we recognise that one of the things blocking further expansion/adoption is that people worry they don't have a complete picture of everything that is happening then I think we should look at supporting alternate methods.

Thoughts?

**Comment by sjmcculloch** [comment]
I think that is the correct model about users existing outside of an organisation and a person existing within an organisation. Potentially a user can be associated with many people across different organisations. 

I agree about leaving complexity response types (manual, sms, etc) out of the system for now but allow them to potentially mark someone as attending as a UI feature. The app will need to know who is attending (regardless of how they respond) so it can standup the team. Is that a correct assumption? I'm still a little unclear on how the app creates the team in this circumstance.

**Comment by sdunster** [comment]
afaict the app does not need to have a concept of a team at all. I expect it to expose an API that beacon could use to fetch the current responders to an event to help with pre-filling a team or something like that. My intention is to just build a way to coordinate people getting to HQ or a rescue directly and leave it at that. Once responders are at HQ or a job they tend to coordinate via radio or other means. It might be fun to add a chat room or even PTT voice chat in future though.
