### ISSUE TITLE
Availability Notes

### ISSUE THREAD

**Issue by sjmcculloch** [NSWSESMembers/availability-poc#123]
_[1.47] Users may optionally record notes against any availability._

There doesn't appear to be a location for storing notes on availability - let's add it in at both the schedule and timesegment.

**Comment by OSPFNeighbour** [comment]
would need to be added to TimeSegmentModel. schedule has a description already and would not be per user if kept there.

**Comment by sjmcculloch** [comment]
My original reading of the requirements indicated that schedules were stored against a user (not a group) e.g. similar to how I setup schedules in my calendar. 

Was this always meant to be associated with a group?

**Comment by OSPFNeighbour** [comment]
It currently is associated to a group and from our dev work and planning weekend has been.

**Comment by OSPFNeighbour** [comment]
Regarding 'like a calendar'. We discussed that approach on the weekend and it was pretty complicated to work out what users should have what schedule, and that having the users schedules under the group allowed for this logic and gave units flexibility around what they collected from members.

Front end we can display it like a calendar overlay, but backend data is what we wanted to make sane.

**Comment by sjmcculloch** [comment]
Okay - I'll follow up with the internal stakeholders and make sure everyone is on the same page.

**Comment by sdunster** [comment]
Yeah the "schedule" model should be thought about as a "shared calendar". Any "TimeSegment" (you can just think of this as a calendar event) is owned by a single user.

It's worth noting a single user could have an available time segment on one schedule and an unavailable time segment on another (for the same time). This is to support the idea that a user might be available for RCR but not for FR due to currency or illness or something. Each unit/group can decide whether they want to have seperate schedules for things or one unified schedule for the entire unit. We'll probably need to do more work here but I think this is a good starting point to run with.
