### ISSUE TITLE
Availability Time Increments

### ISSUE THREAD

**Issue by sjmcculloch** [NSWSESMembers/availability-poc#125]
The requirements say:

_[1.37] The default time increments for availability can be configured in settings (e.g. 15min, 30min, 1hr, 3hr, 6hr, 12hr, 24hr). The default is 1hr (assumed)._

This is configured at a "user" level. How does the data model handle this when a schedule is stored at a group level?

**Comment by OSPFNeighbour** [comment]
do it in the UI not at the data store.

**Comment by sjmcculloch** [comment]
You are going to persist it locally then (through app restarts?)

**Comment by OSPFNeighbour** [comment]
Yea. Andrews UI mock for this had you able to save your own blocks and reuse them which I believe would satisfy this requirement.

**Comment by sjmcculloch** [comment]
Ok - what about the user vs group schedule? Is group schedule the way we are going? I initially thought it was for a user on my reading of the requirements.

**Comment by OSPFNeighbour** [comment]
No concept of user vs group schedule, they are the same.

**Comment by sjmcculloch** [comment]
Ok - maybe the schema isn't setup correctly - it has schedules belonging to owner only (re: data model).

**Comment by OSPFNeighbour** [comment]
Humm not sure which you are looking at.

Groups have Schedules. Schedules have timesegments, user has multiple time segments. from that relationship you can see "all time segments for user X for schedule Y"

**Comment by sjmcculloch** [comment]
The definition of a user being able to define his own schedules is where I misunderstood - if this is not the case (I'll check with the BA's) - we can ignore this. 

I assume also we can have a timeSegment without a schedule (e.g. I am going away on leave for 2 weeks) - it says in the schema that a timeSegment belongs to a schedule.

**Comment by OSPFNeighbour** [comment]
OOoooooooh.

We have no concept of a user making their own time segments without a schedule in our current logic. It was discussed at the hack for a few hours.

Logic behind our decision was that if no one has asked for your availability a) we assume you are available and b) we dont want you to have to fill it in.

Multiple people at the hack had units where they don't track the availability of all members at all times and having members constantly put in times would be a waste of time. When requested of them they could put in their times (and the UI for using pre-saved/set block would make that work).

Example:

User of unit Parramatta is in group Parramatta. Parramatta has no schedules defined. Parramatta needs to find out who can do storm jobs next week because there is a storm forecast. Someone opens up a schedule for next week, members fill it in. User X has already preset some handy time blocks so they use them to fill it in (eg, 09.00-17.00 unavailable)

**Comment by sjmcculloch** [comment]
Thanks Tim - that makes sense - I'll discuss internally and adjust the requirements to reflect if they are agreed. The requirements are in various states and with people coming/going from the project we'll need to be clear on what has been requested.

**Comment by sdunster** [comment]
TimeSegments store unix timestamps which have second-granularity. The API will support this. The clients we build initially might only support 1 hour granularity and eventually might allow the user to configure the granularity and possibly even per-schedule. Point is that the granularity is a UI-thing - clients can store whatever they like down to the second. What they will actually display is another great question but I think we can defer the answer/decision until later since second-granularity I'm sure will support whatever it is we decide to build.

Regarding someone blacking themselves out for 2 weeks due to holidays or something I'd imagine this is implemented by simply making an API call that fetches every schedule a user is a member of and inserts an unavailable time segment for the period. It's hacky but I think it will work for what we need. If we want to store these things as overrides attached directly to the user model later we could do that. We could even re-use the existing TimeSegment model and just have the schedule set to `NULL`/`0` as a global override or something.

**Comment by sjmcculloch** [comment]
I was initially thinking override attached to the user model rather than blanking out existing schedules (which may overlap) and I might still be available for *some* of the schedule.

When I first looked at this project, availability schedules seemed to be the most complex part of the project from a data perspective.

**Comment by sjmcculloch** [comment]
Closing discussion
