### ISSUE TITLE
Device is not associated to user on user signup and errors are not returned to user

### ISSUE THREAD

**Issue by OSPFNeighbour** [NSWSESMembers/availability-poc#19]
Unhandled rejection SequelizeEagerLoadingError: device is not associated to user!

when a user signs up

**Comment by sdunster** [comment]
We need to make sure the following return all promises back to be resolved by graphql so that all errors are caught and handled appropriately and it actually fails the tests instead of silently succeeding:
* login mutation
  * load user
  * device creation/check
  * jwt generation (not sure if async or not)
* signup mutation
  * user creation
  * device creation
  * jwt generation (not sure if async or not)

https://github.com/NSWSESMembers/availability-poc/blob/master/server/src/resolvers.js#L52

**Comment by sdunster** [comment]
Pretty sure this is no longer a thing - reopen if it is.
