### ISSUE TITLE
HQ's (Entities) Data Feed

### ISSUE THREAD

**Issue by sjmcculloch** [NSWSESMembers/availability-poc#81]
HQ's (entities) will need be exposed to the availability application (mobile/web).

1. Define the data structure of HQs

2. Provide hard coded json fixture in /app/fixtures/entities.js (Is entities the terminology you want to use in the app @sdunster ?)

3. Provide API interface from Beacon to retrieve entities

**Comment by sjmcculloch** [comment]
Proposed data format:
{
   "id":1,
   "name":"State Headquarters",
   "code":"SHQ",
   "latitude":0.000000,
   "longitude":0.000000,
   "children":[
      {
         "id":2,
         "name":"Hunter Region",
         "code":"HUR",
         "latitude":0.000000,
         "longitude":0.000000
      }
}

It would continue to be nested under each node.

**Comment by sjmcculloch** [comment]
Duplicate of #128

**Comment by sdunster** [comment]
Availability only understands groups currently. Trying to keep it simple. In the future we could use something generic like entities that contain groups but I don't really like the word cause it is often used to refer to DB rows, graph nodes or ORM instances. If we decide to create another level of organisation I suggest we discuss the term to use then. For the SES API I think calling it entities is fine if that's what makes sense from your side. Otherwise (since the API is SES-specific) calling them units, HQs, regions etc is fine.

**Comment by sjmcculloch** [comment]
Entities is a very poor name from my perspective. 

For the initial cut, it will be Units. The intent is to provide an interface we can add on to overtime for Beacon so you might need this data at all (but it will be there if you do).

I would say availability groups are more closer aligned to contact groups.
