### ISSUE TITLE
Groups Screen - Dupes

### ISSUE THREAD

**Issue by Sprooty** [NSWSESMembers/availability-poc#91]
Dupes of Groups showing on "groups" screen. Android.

**Comment by sdunster** [comment]
screenshot or more detail plz

**Comment by Sprooty** [comment]
- Login
- Groups Tab > Find and Join Groups
- Tap "Wollongong" 3 times
- Go back to Groups overview
- Note "Wollongong" group is listed 3 times.

**Comment by sdunster** [comment]
I think this will be mostly fixed by #97.
I opened #109 to ensure this never happens on the server side.

**Comment by OSPFNeighbour** [comment]
Not technically a bug because you really are in the group 3 times

On 5 Dec. 2017 8:47 am, "Sam Dunster" <notifications@github.com> wrote:

I think this will be mostly fixed by #97
<https://github.com/NSWSESMembers/availability-poc/pull/97>.
I opened #109 <https://github.com/NSWSESMembers/availability-poc/issues/109>
to ensure this never happens on the server side.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/NSWSESMembers/availability-poc/issues/91#issuecomment-349117052>,
or mute the thread

**Comment by sjmcculloch** [comment]
No longer an issue - the screens have been redesigned.
